/** ABIs + deployed addresses. SCAFFOLD — imports contracts/deployments/*.json (T7/T24). */
export const REGISTRY_ADDRESS = import.meta.env.VITE_REGISTRY_ADDRESS ?? "";
// TODO(T7): export ABIs generated by hardhat typechain.
